- name: apt-get update
  apt:
    update_cache: yes
    upgrade: yes

- name: install packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common